### ISSUE TITLE
[Crafting] Dupe item

### ISSUE THREAD

**Issue by BrainRTP** [mmopluginteam/mmoitems#167]
Found a bug with crafting, in which an item is duped.
Video and item settings are attached below.

**MMOItems version 5.5.3-SNAPSHOT**
**Paper version git-Paper-380 (MC: 1.15.2)**

```yaml
1_SWORD2_POISON:
  material: WOODEN_SWORD
  max-durability: 200.0
  unbreakable: true
  attack-speed: 0.8
  attack-damage: 4.0
  displayed-type: Меч
  tier: COMMON
  name: '&2Меч чертополоха'
  lore:
  - '&6При ударе накладывает на противника'
  - '&6отравление 1 уровня на 5 секунд.'
  - ''
  - '&6Перезарядка: &96.5 секунд'
  - ''
  - '&7Запас прочности: &f200'
  will-break: true
  critical-strike-power: 20
  critical-strike-chance: 56.5
  hide-enchants: true
  craft-enabled: true
  crafting:
    shaped:
      '1':
      - AIR MATERIAL.FERMENTED_SPIDER_EYE AIR
      - AIR MATERIAL.WOODEN_SWORD AIR
      - AIR AIR AIR
  ability:
    ability1:
      type: POISON
      mode: ON_HIT
      duration: 5.0
      cooldown: 6.5
  required-level: 1.0
```

Video: https://youtu.be/Uu9XjfZYeqg
Full MMOItems archive: [MMOItems.tar.gz](https://github.com/mmopluginteam/mmoitems/files/4972187/MMOItems.tar.gz)
