### ISSUE TITLE
Could not register the type SKIN: Could not find config for SKIN

### ISSUE THREAD

**Issue by mibby** [mmopluginteam/mmoitems#205]
**Please include a `latest.log`**
https://paste.gg/p/anonymous/26d75ae980d44dd882a0766b133d75c9/files/84f06938830747ddbdd4c77e16237f84/raw

**Describe the bug**
```
[18:37:59] [Server thread/INFO]: [MMOItems] Loading MMOItems v5.5.4
[18:37:59] [Server thread/INFO]: [MMOItems] Hooked onto WorldGuard
[18:37:59] [Server thread/WARN]: [MMOItems] Could not register the type SKIN: Could not find config for SKIN
```

**To Reproduce**
1. Start server.
2. See initialization warning.

**Expected behavior**
No warning.

**Server info:**
 - Tuinity dev 333 (Paper Fork - Spigot 1.16.1)
 - MMOItems dev 3385

**Additional context**
I could not find any skin setting in the main config of MMOItems. The only skin related setting available is;

```
# When this is set to true, skins can only be applied to an item ONCE. 
locked-skins: true
```

Is this a conflict with Citizens or LibsDisguise? What is type SKIN?

**Comment by Indyuce** [comment]
Try adding this to your item-types.yml
```
SKIN:
    display: LEATHER
    name: 'Skin'
    unident-item:
        name: '&f#prefix#Unidentified Skin Item'
        lore:
        - '&7This item is unidentified. I must'
        - '&7find a way to identify it!'
        - '{tier}'
        - '{tier}&8Item Info:'
        - '{range}&8- &7Lvl Range: &e#range#'
        - '{tier}&8- &7Item Tier: #prefix##tier#'
```
